### ISSUE TITLE
Running ES 8.8.0 in Colab

### ISSUE THREAD

**Issue by efung** [HamidRezaAttar/Elasticsearch-Jupyter-Colab#1]
Have you tried running a newer ElasticSearch following your notebook? (I'm using a free Colab account BTW)

I'm getting this error when I look at the logs:

```
[2023-06-09T20:55:09,286][ERROR][o.e.b.Elasticsearch      ] [c96a2bd9070a] fatal exception while booting Elasticsearch java.security.AccessControlException: access denied ("java.io.FilePermission" "/sys/fs/cgroup/../../jupyter-children/cpu.stat" "read")
```

It sounds like Colab is not letting ES read some information from the Linux kernel!?

Easiest way to see these logs is to run this in a cell (rather than trying to launch the daemon via Python):

```
%%bash
sudo -u daemon elasticsearch-8.8.0/bin/elasticsearch -d -p pid
```

**Comment by HamidRezaAttar** [comment]
@efung I did some R&D on ElasticSearch 8.8.0 and I noticed some changes that needed to be applied to notebooks. You can check them out in a new notebook I just pushed. If this solves your problem make sure to leave a star 🙂. When I started this repo I was trying to use ES 7.14 which ended up using 7.0 because of the same problems. I hope this approach helps.

**Comment by efung** [comment]
Awesome, thanks for posting the updated notebook. It's working for me!
